name: Move PR to "In Pull Request"

on:
  pull_request:
    types: [opened]

jobs:
  update-project-board:
    runs-on: ubuntu-latest
    steps:
      - name: Move PR to "In Pull Request"
        uses: actions/add-to-project@v0.1.0
        with:
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> d9c6628 ([#55] project url 수정)
=======
>>>>>>> 64294e1 ([#55] Github Actions workflow 추가)
=======
=======
>>>>>>> 97ed6b2 ([#55] project url 수정)
=======
>>>>>>> 57e9b71 ([#55] project url 수정)
=======
>>>>>>> 71dcb9d ([#55] Github Actions workflow 추가)
=======
>>>>>>> 06dcf18 ([#55] project url 수정)
>>>>>>> 9be8860 ([#55] project url 수정)
=======
>>>>>>> 824d49d ([#55] project url 수정)
=======
>>>>>>> e1a5111 ([#55] Github Actions workflow 추가)
=======
=======
>>>>>>> 06dcf18 ([#55] project url 수정)
>>>>>>> 860dd9e ([#55] project url 수정)
=======
>>>>>>> 7d8adaa ([#55] project url 수정)
=======
=======
>>>>>>> b8ce79a ([#55] Github Actions workflow 추가)
=======
>>>>>>> d9c6628 ([#55] project url 수정)
>>>>>>> 51848de ([#55] project url 수정)
=======
>>>>>>> 64294e1 ([#55] Github Actions workflow 추가)
=======
>>>>>>> e6dab41 ([#55] Github Actions workflow 추가)
=======
>>>>>>> 8eea315 ([#55] project url 수정)
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> fbbcfeb ([#55] project url 수정)
=======
>>>>>>> d9c6628 ([#55] project url 수정)
=======
=======
>>>>>>> 9be8860 ([#55] project url 수정)
=======
>>>>>>> e1a5111 ([#55] Github Actions workflow 추가)
=======
>>>>>>> 860dd9e ([#55] project url 수정)
=======
>>>>>>> 97ed6b2 ([#55] project url 수정)
=======
>>>>>>> 57e9b71 ([#55] project url 수정)
=======
>>>>>>> 71dcb9d ([#55] Github Actions workflow 추가)
=======
=======
>>>>>>> e6dab41 ([#55] Github Actions workflow 추가)
>>>>>>> e844bde ([#55] Github Actions workflow 추가)
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> 64294e1 ([#55] Github Actions workflow 추가)
=======
=======
>>>>>>> 06dcf18 ([#55] project url 수정)
<<<<<<< HEAD
>>>>>>> 9be8860 ([#55] project url 수정)
=======
>>>>>>> 4f36fc0 ([#55] project url 수정)
=======
>>>>>>> 824d49d ([#55] project url 수정)
=======
>>>>>>> e1a5111 ([#55] Github Actions workflow 추가)
=======
=======
>>>>>>> 06dcf18 ([#55] project url 수정)
>>>>>>> 860dd9e ([#55] project url 수정)
=======
=======
=======
>>>>>>> fbbcfeb ([#55] project url 수정)
>>>>>>> 7d8adaa ([#55] project url 수정)
<<<<<<< HEAD
>>>>>>> 97ed6b2 ([#55] project url 수정)
=======
=======
=======
>>>>>>> b8ce79a ([#55] Github Actions workflow 추가)
=======
>>>>>>> fbbcfeb ([#55] project url 수정)
=======
>>>>>>> d9c6628 ([#55] project url 수정)
<<<<<<< HEAD
>>>>>>> 51848de ([#55] project url 수정)
<<<<<<< HEAD
>>>>>>> 57e9b71 ([#55] project url 수정)
=======
=======
=======
=======
=======
>>>>>>> e6dab41 ([#55] Github Actions workflow 추가)
>>>>>>> e844bde ([#55] Github Actions workflow 추가)
>>>>>>> 64294e1 ([#55] Github Actions workflow 추가)
>>>>>>> b8ce79a ([#55] Github Actions workflow 추가)
>>>>>>> 71dcb9d ([#55] Github Actions workflow 추가)
          project-url: "https://github.com/orgs/DeveloperAcademy-POSTECH/projects/163"
=======
          project-url: "https://github.com/DeveloperAcademy-POSTECH/2024-MacC-A16-AGAMI"
>>>>>>> 628925b ([#55] Github Actions workflow 추가)
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> d9c6628 ([#55] project url 수정)
=======
=======
>>>>>>> 9be8860 ([#55] project url 수정)
=======
>>>>>>> 860dd9e ([#55] project url 수정)
=======
>>>>>>> 97ed6b2 ([#55] project url 수정)
=======
>>>>>>> 57e9b71 ([#55] project url 수정)
=======
>>>>>>> 71dcb9d ([#55] Github Actions workflow 추가)
=======
>>>>>>> e844bde ([#55] Github Actions workflow 추가)
>>>>>>> 64294e1 ([#55] Github Actions workflow 추가)
=======
>>>>>>> 06dcf18 ([#55] project url 수정)
=======
>>>>>>> 824d49d ([#55] project url 수정)
=======
=======
>>>>>>> e844bde ([#55] Github Actions workflow 추가)
>>>>>>> e1a5111 ([#55] Github Actions workflow 추가)
=======
>>>>>>> 06dcf18 ([#55] project url 수정)
=======
>>>>>>> 7d8adaa ([#55] project url 수정)
=======
=======
>>>>>>> b8ce79a ([#55] Github Actions workflow 추가)
=======
>>>>>>> d9c6628 ([#55] project url 수정)
>>>>>>> 51848de ([#55] project url 수정)
=======
=======
>>>>>>> e844bde ([#55] Github Actions workflow 추가)
>>>>>>> 64294e1 ([#55] Github Actions workflow 추가)
=======
          project-url: "https://github.com/orgs/DeveloperAcademy-POSTECH/projects/163"
>>>>>>> 6e06c8b ([#55] project url 수정)
=======
>>>>>>> e6dab41 ([#55] Github Actions workflow 추가)
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 06dcf18 ([#55] project url 수정)
=======
>>>>>>> 824d49d ([#55] project url 수정)
=======
>>>>>>> e1a5111 ([#55] Github Actions workflow 추가)
=======
=======
>>>>>>> 06dcf18 ([#55] project url 수정)
>>>>>>> 860dd9e ([#55] project url 수정)
=======
=======
>>>>>>> 06dcf18 ([#55] project url 수정)
=======
>>>>>>> b8ce79a ([#55] Github Actions workflow 추가)
>>>>>>> 71dcb9d ([#55] Github Actions workflow 추가)
=======
=======
          project-url: "https://github.com/orgs/DeveloperAcademy-POSTECH/projects/163"
>>>>>>> 6e06c8b ([#55] project url 수정)
>>>>>>> 8eea315 ([#55] project url 수정)
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
=======
>>>>>>> 71dcb9d ([#55] Github Actions workflow 추가)
=======
>>>>>>> e844bde ([#55] Github Actions workflow 추가)
=======
>>>>>>> 06dcf18 ([#55] project url 수정)
=======
>>>>>>> 57e9b71 ([#55] project url 수정)
=======
>>>>>>> 51848de ([#55] project url 수정)
=======
>>>>>>> b8ce79a ([#55] Github Actions workflow 추가)
=======
=======
          project-url: "https://github.com/orgs/DeveloperAcademy-POSTECH/projects/163"
>>>>>>> 6e06c8b ([#55] project url 수정)
>>>>>>> fbbcfeb ([#55] project url 수정)
<<<<<<< HEAD
=======
>>>>>>> d9c6628 ([#55] project url 수정)
=======
=======
>>>>>>> e844bde ([#55] Github Actions workflow 추가)
>>>>>>> 64294e1 ([#55] Github Actions workflow 추가)
=======
=======
>>>>>>> 97ed6b2 ([#55] project url 수정)
=======
>>>>>>> e844bde ([#55] Github Actions workflow 추가)
=======
>>>>>>> 06dcf18 ([#55] project url 수정)
<<<<<<< HEAD
>>>>>>> 9be8860 ([#55] project url 수정)
=======
=======
>>>>>>> 97ed6b2 ([#55] project url 수정)
=======
=======
          project-url: "https://github.com/orgs/DeveloperAcademy-POSTECH/projects/163"
>>>>>>> 6e06c8b ([#55] project url 수정)
<<<<<<< HEAD
>>>>>>> 4f36fc0 ([#55] project url 수정)
=======
>>>>>>> 824d49d ([#55] project url 수정)
=======
=======
>>>>>>> e844bde ([#55] Github Actions workflow 추가)
>>>>>>> e1a5111 ([#55] Github Actions workflow 추가)
=======
=======
>>>>>>> e844bde ([#55] Github Actions workflow 추가)
=======
>>>>>>> 06dcf18 ([#55] project url 수정)
>>>>>>> 860dd9e ([#55] project url 수정)
=======
>>>>>>> fbbcfeb ([#55] project url 수정)
>>>>>>> 7d8adaa ([#55] project url 수정)
>>>>>>> 97ed6b2 ([#55] project url 수정)
=======
<<<<<<< HEAD
>>>>>>> 7d8adaa ([#55] project url 수정)
=======
=======
>>>>>>> d9c6628 ([#55] project url 수정)
<<<<<<< HEAD
>>>>>>> 51848de ([#55] project url 수정)
<<<<<<< HEAD
>>>>>>> 57e9b71 ([#55] project url 수정)
=======
=======
=======
=======
>>>>>>> e844bde ([#55] Github Actions workflow 추가)
>>>>>>> 64294e1 ([#55] Github Actions workflow 추가)
>>>>>>> b8ce79a ([#55] Github Actions workflow 추가)
>>>>>>> 71dcb9d ([#55] Github Actions workflow 추가)
          column-name: "In Pull Request"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
